### ISSUE TITLE
Event object returned from GetEventPage() has the zero-value timestamp.

### ISSUE THREAD

**Issue by chatx** [orchestrate-io/gorc2#12]
I think, when the iterator is created, that timestamp  should be set correctly. (https://github.com/orchestrate-io/gorc2/blob/master/iterator.go#L153)

Anyway, as the result GetEventPage() sets 0 for Event.Timestamp. (0/1000 == 0, (0 %1000) * 1000000 == 0)

func (i *Iterator) GetEventPage() ([]*Event, error) {
...
		secs := int64(r.Timestamp / 1000)
		nsecs := int64((r.Timestamp % 1000) * 1000000)
		events = append(events, &Event{
			Collection: i.client.Collection(r.Path.Collection),
			Key:        r.Path.Key,
			Ordinal:    r.Path.Ordinal,
			Ref:        r.Path.Ref,
			Type:       r.Path.Type,
			Timestamp:  time.Unix(secs, nsecs),
			Value:      r.Value,
		})
	}
...

**Comment by liquidgecka** [comment]
I don't think I understand completely. Under what conditions are you getting 0 timestamps? Ideally when you set the Event can you get me the output form fmt.Printf("%#v\n", x) [where x is the object]. That will help me identify what the event should be returning. It is possible at least to iterate events with timestamps (its tested in the unit tests), and I just validated that it is working by hand.

**Comment by chatx** [comment]
It seems that it happens with Search() on event types. Iterators from ListEvents() have correct timestamp values. (the resulting time value doesn't make sense to me either...)

But, in the path objects, both cases have correct ts values.

I tried a simple event test with a test collection table.

1. iterators from ListEvents()

Result: &gorc2.jsonItem{Distance:0, Ordinal:724383500778086400, Path:gorc2.jsonPath{Collection:"Orchestrate API Live Test", Kind:"event", Key:"chatroom1", Ordinal:724383500778086400, Ref:"7421d43bc30c0b15", Timestamp:1402947790001, Tombstone:false, Type:"default"}, RefTime:1431711021245, Score:0, Timestamp:1402947790001, Value:json.RawMessage{0x7b, 0x22, 0x45, 0x4e, 0x43, 0x22, 0x3a, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x2c, 0x22, 0x45, 0x58, 0x50, 0x22, 0x3a, 0x22, 0x30, 0x22, 0x2c, 0x22, 0x49, 0x22, 0x3a, 0x22, 0x31, 0x22, 0x7d}}

Event: &gorc2.Event{Collection:(*gorc2.Collection)(0xc2082638e0), Key:"chatroom1", Ordinal:724383500778086400, Ref:"7421d43bc30c0b15", Timestamp:time.Time{sec:63538544590, nsec:1000000, loc:(*time.Location)(0x8c7dc0)}, Type:"default", Value:json.RawMessage{0x7b, 0x22, 0x45, 0x4e, 0x43, 0x22, 0x3a, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x2c, 0x22, 0x45, 0x58, 0x50, 0x22, 0x3a, 0x22, 0x30, 0x22, 0x2c, 0x22, 0x49, 0x22, 0x3a, 0x22, 0x31, 0x22, 0x7d}}


2. iterators from Search()

Result: &gorc2.jsonItem{Distance:0, Ordinal:0, Path:gorc2.jsonPath{Collection:"Orchestrate API Live Test", Kind:"event", Key:"jsonData", Ordinal:724383517370753024, Ref:"39a93bf9782de6ae", Timestamp:1402947790007, Tombstone:false, Type:"default"}, RefTime:1431711022234, Score:14.080003, Timestamp:0, Value:json.RawMessage{0x7b, 0x22, 0x45, 0x4e, 0x43, 0x22, 0x3a, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x2c, 0x22, 0x45, 0x58, 0x50, 0x22, 0x3a, 0x22, 0x30, 0x22, 0x2c, 0x22, 0x4a, 0x22, 0x3a, 0x7b, 0x22, 0x69, 0x64, 0x22, 0x3a, 0x22, 0x61, 0x62, 0x63, 0x64, 0x65, 0x22, 0x7d, 0x7d}}

Event: &gorc2.Event{Collection:(*gorc2.Collection)(0xc20823b100), Key:"jsonData", Ordinal:724383517370753024, Ref:"39a93bf9782de6ae", Timestamp:time.Time{sec:62135596800, nsec:0, loc:(*time.Location)(0x8c7dc0)}, Type:"default", Value:json.RawMessage{0x7b, 0x22, 0x45, 0x4e, 0x43, 0x22, 0x3a, 0x66, 0x61, 0x

**Comment by liquidgecka** [comment]
I think I am still confused. the jsonItem object shouldn't be used outside of the gorc2 library (its a representation of the json returned from a few different calls). The inner Timestamp (not the one in the jsonPath item) is obsolete and was basically deprecated. In some calls its provided for legacy reasons, in others its not provided at all.. But it is always provided in the path object.

That internal representation (jsonItem) basically collects the data from the json reply, then gets encoded into the Event object returned so that you need not have to worry about stuff like deprecated fields and such. =)

In both cases it looks like the returned Event has its Timestamp field populated with a golang time.Time object which is exactly what should be happening. If you want to boil that value down to a api compatible "milliseconds since epoch" just use event.Timestamp.UnixNano() / 1000000. The special object is provided because it basically deals with all of the crazy complexity of time internally so you do not have to worry about time zones and such.

Did that address your concern? Are you seeing an empty timestamp in any Event objects or is it only that internal representation that shouldn't persist beyond the gorc2 library?

**Comment by chatx** [comment]
Sorry for the confusion. I put printf in the gorc2 source code (in the GetEventPage() function), so that I can see both result and event in the GetEventPage() call.

Then the bug that's causing this issue is:

https://github.com/orchestrate-io/gorc2/blob/master/iterator.go#L371

where Event.Timestamp value is taken from the deprecated item timestamp (see it's not from the timestamp in the path object).

And the event time value that you see printed below is actually what you get when you directly print out  time.Unix(0, 0) object. Please check this out: https://play.golang.org/p/As9KAGHB4L

As I mentioned earlier, this 0 timestamp in item happens when the iterator is generated with Search(), not ListEvents(). 

Please check out and let me know if I'm missing anything here.

-Min

**Comment by liquidgecka** [comment]
Yea absolutely good call! I followed your first link and then got all wrapped up into looking into the GetEvent() function rather than GetEventPage() so now it makes perfect sense what you are reporting! Sorry for getting confused! =)

[And for the love of Pete, every time I see the go timestamps I forget that 0 is not 0.. You think I would remember that by now!] =)

**Comment by chatx** [comment]
I already see the fix for this. Thank you for the quick fix!!

Also, I just found that "secs" in golang time is not in linux time when investigating this issue on our side. :-)
